// <auto-generated />
namespace DauGiaTrucTuyen.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addCreateDate_for_table_User : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCreateDate_for_table_User));
        
        string IMigrationMetadata.Id
        {
            get { return "201902260244366_add-CreateDate_for_table_User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
